name: Setup node and install all dependencies
description: Install all node_modules with a composit action
inputs:
  node-version:
    description: 'Node version that should be passed on to actions/setup-node'
    default: "12"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
    - uses: c-hive/gha-yarn-cache@v2
      shell: yarn install --ignore-scripts