name: Easily make release of a package
description: >
  **Note: This action does not publish a npm (or github) package this should be done manually**

  To make it easy for everyone to make a release of a package you can add this action in your workflow.
  
  All you need to do is:

  - Change the version number in package.json. Either by manually changing it or by running yarn version.
  
  - Add this action to you workflow file


  ### Example

  ```yml

  release:
    name: Make release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - uses: paralenz/actions/make-release@master
  ```

author: Paralenz

inputs:
  token:
    required: false
    description: >
      Auth token for the github package registry.
      This token defaults to the github.token. If you which to overwrite it you can do that
    default: ${{ github.token }}

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - name: Check package version
        uses: PostHog/check-package-version@v2
        id: cpv

      - name: Skip publish
        if: ${{steps.cpv.outputs.is-new-version == 'false' }}
        run: |
          echo "::error Release will not be published. The version number has not been bumped"
          echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
          echo "Published version: ${{ steps.cpv.outputs.published-version }}"
          echo "Is new version: ${{ steps.cpv.outputs.is-new-version }}"
        shell: bash

      - name: Make release
        if: ${{steps.cpv.outputs.is-new-version == 'true' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ inputs.token }}
          prerelease: false
          title: v${{ steps.cpv.outputs.committed-version }}
          automatic_release_tag: v${{ steps.cpv.outputs.committed-version }}