name: Ensure that pull request title starts with a gitmoji
description: The paralenz dev team uses gitmojies to generate changelogs. This action ensures that the PR title starts with one
author: Paralenz
runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - name: Fetch gitmojies from carloscuesta/gitmoji
        run: node ./index.js
        working-directory: './gitmoji'
        id: gitmojies
        shell: bash
      - uses: actions/checkout@v2
      - name: Verify that pull request title starts with a gitmoji
        uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: "${{ steps.gitmojies.outputs.gitmojis }}"
          min_length: 5
          max_length: 72
