name: 'Setup node and install dependencies'
description: Setup node, install and cache dependencies.
author: Paralenz
branding:
  color: gray-dark
  icon: 'aperture'
inputs:
  node-version:
    required: false
    description: 'The node version that should be used'
    default: '16'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  registry-url:
    required: false
    description: 'The registry where the package will be published'
    default: 'https://npm.pkg.github.com/paralenz'
    

runs:
    using: 'composite'
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{inputs.node-version}}
          registry-url: ${{inputs.registry-url}}
        
      - name: Set up GitHub package registry auth token
        run: npm config set //npm.pkg.github.com/:_authToken=${{ inputs.token }}
        shell: bash

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
        shell: bash