name: Send notification to Discord
description: Send a Discord notification with a specific message
author: Paralenz

inputs:
   message:
    required: true
    description: Message to send for discord
   
runs:
    using: 'composite'
    steps:
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ inputs.message }} # 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
