name: Easily publish a new version of a package
description: >
  **Note: This action does not publish a npm package this should be done manually**

  To make it easy for everyone to publish a new version of a package you can add this action in your workflow.
  
  All you need to do is:

  - Change the version number in package.json. Either by manually changing it or by running yarn version.
  
  - Add this action to you workflow file


  ### Example

  ```yml

  publish:
    name: Publish release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - uses: paralenz/actions/publish-release@master
  ```

author: Paralenz

inputs:
  token:
    required: false
    description: >
      Auth token for the github package registry.
      This token defaults to the github.token. If you which to overwrite it you can do that
    default: ${{ github.token }}

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v2
      - uses: paralenz/actions/setup-node@master
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
        shell: bash
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ inputs.token }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
      