name: Pull request

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  job1:
    name: Verify that pull request title starts with a gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - name: Load gitmojies
        id: gitmojies
        uses: juliangruber/read-file-action@v1
        with:
          path: ./gitmojies.json
      - name: Echo gitmojies.json
        run: echo "${{ steps.gitmojies.outputs.content }}"
      # - uses: deepakputhraya/action-pr-title@master
      #   with:
      #     allowed_prefixes: "${{ steps.gitmojies.outputs.content }}" # title should start with the given prefix
      #     min_length: 5
      #     max_length: 72

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/setup-node@master

  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/setup-node@master
      - name: Run Linting
        run: yarn lint
