name: Pull request

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr_title:
    name: Ensure that the pull request title starts with a gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./gitmoji

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node

  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - run: yarn lint
  
  changelog:
    name: Generate changelog
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Read version.txt
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
        run: echo "${{ steps.version.outputs.content }}"

      - name: Changelog
      - uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: v${{ steps.version.outputs.content }}
          to-tag: v${{ steps.extract_version.outputs.version }}
      
      - name: Update version.txt
        run: echo ${{ steps.extract_version.outputs.version }} > version.txt
      
      - name: Commit and push change
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: .
          message: 📝 Update changelog

