name: Pull request

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify that pull request title starts with a gitmoji
        uses: ./gitmoji

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/setup-node@master

  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/setup-node@master
      - name: Run Linting
        run: yarn lint
