name: Pull request

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr_title:
    name: Ensure that the pull request title starts with a gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./gitmoji

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node

  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps: 
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - run: yarn lint
