name: Pull request

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  pr_title:
    name: Ensure that the pull request title starts with a gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./gitmoji

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - run: |
          echo '::warning:: this is a warning'
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo '::warning:: this will NOT be a warning'
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
          echo '::warning:: this is a warning again'

  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - run: yarn lint
  
  release:
    name: Make release
    needs: [setup]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - uses: ./make-release
