name: "Create Release"

on:
  push:
    branches:
      - "master"

jobs:
  setup:
    name: Setup
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - name: Run linting
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Generate Documentation
        run: yarn docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          add: .
          message: 📝 Update documentation
      - name: Create github release
        uses: ./make-release

        