name: "Release"

# on:
#   push:
#     branches:
#       - "master"
on:  
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2  
      - name: Set up GitHub package registry auth token
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn lint

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       LICENSE.txt
      #       *.jar