name: "Create Release"

on:
  push:
    branches:
      - "master"

jobs:
  setup:
    name: Setup
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-node
  
  lint:
    name: Linting
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-node
      - run: yarn lint

  documentation:
    name: Generate documentation based on action.yml files
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-node
      - run: tsc
      - name: Generate Documentation
        run: yarn docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
          add: .
          message: 📝 Update readme.md
  
  release:
    name: Create release
    needs: [documentation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-node
      - uses: ./make-release

        