name: "Create Release"

on:
  push:
    branches:
      - "master"

jobs:
  setup:
    name: Setup
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2  
      - name: Set up GitHub package registry auth token
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Lint
        run: yarn lint
      - name: Build
        run: tsc
      - name: Generate Documentation
        run: |
          node dist/generate-docs.js
      
      - name: Extract next version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Read version.txt
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
        run: echo "${{ steps.version.outputs.content }}"

      - name: Changelog
      - uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: v${{ steps.version.outputs.content }}
          to-tag: v${{ steps.extract_version.outputs.version }}
      
      - name: Update version.txt
        run: echo ${{ steps.extract_version.outputs.version }} > version.txt
      
      - name: Commit and push change
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: .
          message: 📝 Update documentation for packages

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
        