name: Temp

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-node
      - uses: ./discord
        with:
          webhook: https://discord.com/api/webhooks/946770783190024193/WYPHnSx011e5nLxKEIGDovNLYHADaeHaBgTZNW9OMcqMuPLKjRtjGcd3nT6A_hSRuPna
          title: Carsten is testing
          description: Does this really work?

